env:
  DEBUG: true

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js v20 using nvm
        uses: nvm-sh/action@v1
        with:
          node_version: 20

      - name: Upload SSH key
        uses: actions/upload-artifact@v3
        with:
          name: ssh-key

      - name: Setup SSH on remote server
        run: |
          ssh-keyscan ${{ secrets.IP }} >> ~/.ssh/known_hosts

      - name: Download SSH key from artifact
        uses: actions/download-artifact@v3
        with:
          name: ssh-key

      - name: Add SSH key to agent
        run: |
          chmod 600 ssh-key
          ssh-add ssh-key

      - name: Deploy using SSH
        run: |
          #!/bin/bash

          # Change directory to project directory
          cd /var/www/bimcopilot

          # Update package lists (optional)
          # apt update

          # Install dependencies (if needed)
          # apt install some-package -y

          # Print Node.js and npm versions for troubleshooting
          node -v
          npm -v

          # Pull latest changes from git
          git pull origin main

          # Use nvm to install or update npm to v20
          nvm install 20

          # Install or update npm dependencies
          npm install -f

          # Build production folder
          npm run build

          # Restart PM2 process
          pm2 start next

          # Restart Apache server
          systemctl restart apache2

          # End of script
